# Generated by Django 5.2 on 2025-04-22 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_api', '0003_alter_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhomeworkresult',
            name='answers',
        ),
        migrations.AddField(
            model_name='task',
            name='is_auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Учитель курса'),
        ),
        migrations.CreateModel(
            name='UserTaskAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('answers_text', models.CharField(blank=True, max_length=1023)),
                ('answers_files', models.FileField(blank=True, upload_to='user_task_answers_foto/')),
                ('correct_answer', models.CharField(blank=True, max_length=1023)),
                ('is_auto', models.BooleanField(default=True)),
                ('result', models.IntegerField(default=0)),
                ('homework_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_results', to='learn_api.userhomeworkresult')),
            ],
        ),
    ]
