# Generated by Django 5.2 on 2025-04-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_api', '0004_remove_userhomeworkresult_answers_task_is_auto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ball',
            field=models.IntegerField(default=1),
        ),
    ]
