# Generated by Django 5.2 on 2025-04-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_api', '0005_task_ball'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhomeworkresult',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
