# Generated by Django 5.2 on 2025-04-24 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn_api', '0007_taskfile_taskimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskImage',
        ),
    ]
