# Generated by Django 5.2 on 2025-04-25 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_api', '0009_lessonfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTaskAnswerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='usertaskanswer_files/')),
                ('usertaskanswer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='learn_api.usertaskanswer')),
            ],
        ),
    ]
