# Generated by Django 5.2 on 2025-04-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn_api', '0010_usertaskanswerfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertaskanswer',
            name='answers_files',
        ),
    ]
