# Generated by Django 5.2 on 2025-04-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_api', '0011_remove_usertaskanswer_answers_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
