# Generated by Django 5.2 on 2025-04-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_api', '0012_alter_user_date_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание урока'),
        ),
    ]
