# Generated by Django 5.2 on 2025-04-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_api', '0013_lesson_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='month',
            field=models.IntegerField(choices=[('Январь', 1), ('Февраль', 2), ('Март', 3), ('Апрель', 4), ('Май', 5), ('Июнь', 6), ('Июль', 7), ('Август', 8), ('Сентябрь', 9), ('Октябрь', 10), ('Ноябрь', 11), ('Декабрь', 12)], default=1, verbose_name='Месяц'),
        ),
    ]
