# Generated by Django 5.2 on 2025-05-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_api', '0014_alter_course_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='month',
            field=models.CharField(choices=[('Январь', 1), ('Февраль', 2), ('Март', 3), ('Апрель', 4), ('Май', 5), ('Июнь', 6), ('Июль', 7), ('Август', 8), ('Сентябрь', 9), ('Октябрь', 10), ('Ноябрь', 11), ('Декабрь', 12)], default='Январь', verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(choices=[('Информатика', 1), ('Математика профильная', 2), ('Математика базовая', 3), ('Математика', 4), ('Физика', 5), ('Русский язык', 6), ('Английский язык', 7), ('Литература', 8), ('Биология', 9), ('Химия', 10), ('История', 11), ('Обществознание', 12)], default='Информатика', verbose_name='Название предмета'),
        ),
    ]
