# Generated by Django 5.2 on 2025-05-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_api', '0015_alter_course_month_alter_course_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
